version: "2"

services:
    mongo:
        image: mongo:4.1.8-xenial
        container_name: mongo
        restart: unless-stopped
        env_file: .env
        command: mongod
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
    api:
        image: api
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: node index.js
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=mongo
            - MONGO_DB_NAME=$MONGO_DB_NAME
        ports:
            - 8000:8000
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
        depends_on:
            - mongo
        


    #mongo-express:
    #    # Visit http://localhost:8081/ to enter the mongodbpanel
    #    image: mongo-express
    #    container_name: mongo-express
    #    restart: unless-stopped
    #    ports:
    #        - 8081:8081
    #    networks:
    #        - app-network
    #    depends_on:
    #        - mongo
    #    environment:
    #        ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
    #        ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD

    
networks:
    app-network:
        driver: bridge
    
volumes:
    dbdata:
    node_modules: